### ISSUE TITLE
Merge ins Projektrepo

### ISSUE THREAD

**Issue by hermsdorfkonrad** [hermsdorfkonrad/ES_BelegAbgabe#1]
Dieses Repository ist eigentlich unnütz und kann im Grunde 1:1 ins "doc" Verzeichnis des Projektrepository wandern. Das hätte dann den angenehmen Nebeneffekt, dass die ganzen .tex Dateien in einem Ordner lägen und der Latex Compiler auch tatsächlich ein PDF erzeugen würde.

Hast du Einwände? Sonst würde ich das zeitnah noch machen und dann wäre der Beleg auch eigentlich fertig.

**Comment by cowimmer** [comment]
Nein das klingt super! Mir ist noch aufgefallen, dass das ToDo File im Doxy zu sehen ist. Das gehört mmn nicht rein, bzw kann ja sowieso gelöscht werden

**Comment by hermsdorfkonrad** [comment]
Alles klar, ja das ist ein Schalter in der doxy_config, da lass ich das raus
